# Generated by Django 5.0.2 on 2024-02-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Version', models.CharField(max_length=128)),
                ('Description', models.CharField(max_length=128)),
                ('DownloadURL', models.CharField(max_length=1024)),
            ],
        ),
    ]
